analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - directives_ordering
    - no_duplicate_case_values
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
